language: node_js
os: linux
node_js:
  node
before_script:
  npm run build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GH_TOKEN
  target_branch: master
  local_dir: build
  on:
    branch: release
notifications:
  email: false
